### ISSUE TITLE
Bot disconnects all the time

### ISSUE THREAD

**Issue by apinjic** [Akvanvig/disosRemind#2]
My Discord experience is ruined. I hope you have an AWFUL day.

**Comment by picccard** [comment]
My day HAVE BEEN AWFUL, thank you. Now can you please give some details about the problem so we might fix it?

**Comment by apinjic** [comment]
Found a fix, nvm.

**Comment by MrOctopus** [comment]
won't fix

**Comment by apinjic** [comment]
Do NOT close this without my approval!!!!! :)

lør. 16. mai 2020, 23:22 skrev MrOctopus <notifications@github.com>:

**Comment by MrOctopus** [comment]
goass
